url: http://eaps.org.au
baseurl:

# Site settings
title: EAPS18
email: your-email@domain.com
description: "EMBL Australia Postgraduate Symposium 2018"

people:
- name: TBA
  pic: placeholder
  theme: Ecology
  id: Ecology

- name: TBA
  pic: placeholder
  theme: Oncology
  id: Oncology

- name: TBA
  pic: placeholder
  theme: Neurobiology
  id: Neurobiology

- name: TBA
  pic: placeholder
  theme: Bioinformatics
  id: Bioinformatics

- name: TBA
  pic: placeholder
  theme: Genetics and Cell Biology
  id: Genetics_and_Cell_Biology

- name: TBA
  pic: placeholder
  theme: Virology and Immunology
  id: Virology_and_Immunology

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/EMBLAphdsymposium/
  - title: twitter
    url: https://twitter.com/EMBLAuSymposium

# Build settings
markdown: kramdown
permalink: pretty
sass:
    style: compressed
