url: http://eaps.org.au
baseurl: /newsite

# Site settings
title: EAPS18
email: your-email@domain.com
description: "EMBL Australia Postgraduate Symposium 2018"


# Team names, titles and social links
people:
- name: Mystery Speaker
  pic: placeholder
  position: TBA

- name: Mystery Speaker
  pic: placeholder
  position: TBA


- name: Mystery Speaker
  pic: placeholder
  position: TBA


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/EMBLAphdsymposium/
  - title: twitter
    url: https://twitter.com/EMBLAuSymposium


# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
